py_library(

    name = "math_utils",

    srcs = ["math_utils.py"],

    visibility = ["//visibility:public"],

)
 
py_library(

    name = "string_utils",

    srcs = ["string_utils.py"],

    visibility = ["//visibility:public"],

)
 
